elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
  volumes:
    - "./elasticsearch/log:/usr/share/elasticsearch/log"
    - "./elasticsearch/data:/usr/share/elasticsearch/data"

kibana:
  image: kibana:latest
  volumes:
    - ./kibana/config/:/opt/kibana/config/
  ports:
    - "5601:5601"
  links:
    - elasticsearch